CREATE DATABASE libreria_guillermo;

USE libreria_guillermo;

CREATE TABLE AUTOR (
ID_AUTOR INT PRIMARY KEY AUTO_INCREMENT NOT NULL UNIQUE, 
NOMBRE VARCHAR(50) NOT NULL DEFAULT 'Anonimo' , 
NACIONALIDAD VARCHAR(50),
FECHA_NACIMIENTO DATE
);

CREATE TABLE EDITORIAL (
ID_EDITORIAL INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
NOMBRE VARCHAR (50) NOT NULL,
DIRECCION VARCHAR (100),
TELEFONO VARCHAR (100) NOT NULL DEFAULT  'OO-0000-0000',
CORREO VARCHAR (100) NOT NULL 
);

CREATE TABLE PROVEEDOR (
ID_PROVEEDOR INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
NOMBRE VARCHAR (50) NOT NULL,
DIRECCION VARCHAR (100),
TELEFONO VARCHAR (100) NOT NULL DEFAULT  'OO-0000-0000',
ID_EDITORIAL INT, 
FOREIGN KEY (ID_EDITORIAL) REFERENCES EDITORIAL (ID_EDITORIAL) 
);

CREATE TABLE LIBRO (
ID_LIBRO INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT, 
TITULO VARCHAR(100) NOT NULL,
ANO_PUBLIACION YEAR, 
GENERO VARCHAR(100),
PRECIO DECIMAL NOT NULL, 
CANTIDAD_DISPONIBLE INT,
ID_AUTOR INT, 
FOREIGN KEY (ID_AUTOR) REFERENCES AUTOR (ID_AUTOR), 
ID_EDITORIAL INT, 
FOREIGN KEY (ID_EDITORIAL) REFERENCES EDITORIAL (ID_EDITORIAL) 
);

CREATE TABLE CLIENTE (
ID_CLIENTE INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT, 
NOMBRE VARCHAR (50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL, 
DIRECCION VARCHAR (100),
TELEFONO VARCHAR (100) NOT NULL DEFAULT  'OO-0000-0000',
CORREO VARCHAR (100)
);

CREATE TABLE VENTA (
ID_VENTA INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT, 
FECHA_VENTA DATE, 
TOTAL PRECIO DECIMAL, 
ID_CLIENTE INT, 
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE TABLE RESEGNA (
ID_RESEGNA INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
CALIFICACION INT, NOT NULL,
COMENTARIO VARCHAR (500), 
FECHA DATE, 
ID_LIBRO INT, 
FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO (ID_LIBRO), 
ID_CLIENTE INT, 
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE TABLE EMPLEADOS (
ID_EMPLEADO INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT, 
NOMBRE VARCHAR (50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL, 
CARGO VARCHAR (50) NOT NULL, 
FECHA_CONTRATACION DATE NOT NULL, 
ELEFONO VARCHAR (100) NOT NULL DEFAULT  'OO-0000-0000',
CORREO VARCHAR (100), 
);
